type Task {
    id: ID!
    createdBy: User! @belongsTo(relation: "createdBy")
    updatedBy: User @belongsTo(relation: "updatedBy")
    title: String!
    description: String
    status: TaskStatus
    priority: TaskPriority
    order: Int
    created_at: DateTime!
    updated_at: DateTime!
}

enum TaskStatus {
    PENDING @enum(value: "pending")
    COMPLETED @enum(value: "completed")
}

enum TaskPriority {
    LOW @enum(value: "low")
    MEDIUM @enum(value: "medium")
    HIGH @enum(value: "high")
}

input TaskInput {
    id: ID
    createdBy: ConnectUserRelation
    updatedBy: ConnectUserRelation
    title: String
    description: String
    status: TaskStatus
    priority: TaskPriority
    order: Int
    updated_at: DateTime
}

input ConnectTaskRelation {
    id: ID
    connect: ID
    upsert: TaskInput
    delete: ID
}

extend type Query {
    tasks: [Task]! @all
    tasksPaginate(
        first: Int!
        page: Int
        search: String @scope(name: "search")
        sort: SortInput @scope(name: "sort")
        filter: [FilterInput] @scope(name: "filter")
        where: _ @whereConditions(columns: ["status", "created_by"])
    ): [Task]! @paginate
    tasksCount: Int! @count(model: "Task")
}

extend type Mutation {
    upsertTask(input: TaskInput!): Task @field(resolver: "App\\GraphQL\\Resolvers\\TaskResolver@upsertTask")
    deleteTask(id: [ID!] @eq): [Task] @delete
}
